import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface ReportData {
  companyName: string
  country: string
  countryCode: string
  industry: string
  naceCode: string
  headcount: number
  reportingYear: string
  scope1: number
  scope1Stationary: number
  scope1Fleet: number
  scope2Location: number
  scope2Market: number
  scope3: number
  total: number
  perEmployee: number
  monthlyData: {
    month: string
    scope1: number
    scope2: number
    scope3: number
    total: number
  }[]
  gridCountry: string
  gridLocation: number  // gCO2/kWh
  gridMarket: number    // gCO2/kWh
}

export type { ReportData }

// ── Helper: safe percent ──
function pct(value: number, total: number): string {
  if (!total || total === 0) return '0.0%'
  return ((value / total) * 100).toFixed(1) + '%'
}

// ── Helper: add footer to all pages ──
function addFooters(doc: jsPDF, label: string) {
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(7)
    doc.setTextColor(180, 180, 180)
    doc.text(
      `${label} · Generated by Hosmos · ${new Date().toISOString().split('T')[0]} · Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    )
  }
}

// ════════════════════════════════════════════════════════════════════════════
//  GRI Standards 2021 Report
// ════════════════════════════════════════════════════════════════════════════

export function generateGRIReport(data: ReportData): jsPDF {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  // ── Header ──
  doc.setFillColor(59, 130, 246) // blue-500
  doc.rect(0, 0, pageWidth, 40, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('GRI Standards 2021 Report', 14, 20)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`${data.companyName} · Reporting Year ${data.reportingYear}`, 14, 32)

  y = 55
  doc.setTextColor(0, 0, 0)

  // ── GRI 2: General Disclosures ──
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('GRI 2: General Disclosures', 14, y)
  y += 10

  autoTable(doc, {
    startY: y,
    head: [['GRI Disclosure', 'Description', 'Value']],
    body: [
      ['GRI 2-1', 'Organization name', data.companyName],
      ['GRI 2-1', 'Country of headquarters', `${data.country} (${data.countryCode})`],
      ['GRI 2-6', 'Industry / Sector', data.industry],
      ['GRI 2-6', 'NACE code', data.naceCode],
      ['GRI 2-7', 'Total employees', String(data.headcount)],
      ['GRI 2-3', 'Reporting period', `January – December ${data.reportingYear}`],
      ['GRI 2-3', 'Report publication date', new Date().toISOString().split('T')[0]],
      ['GRI 2-5', 'External assurance', 'Not yet obtained'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 8 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 28 }, 1: { cellWidth: 55 } },
  })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 15

  // ── GRI 305: Emissions ──
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('GRI 305: Emissions', 14, y)
  y += 10

  autoTable(doc, {
    startY: y,
    head: [['GRI Disclosure', 'Category', 'tCO2e', '% of Total']],
    body: [
      ['GRI 305-1', 'Scope 1 — Stationary combustion', data.scope1Stationary.toFixed(2), pct(data.scope1Stationary, data.total)],
      ['GRI 305-1', 'Scope 1 — Company fleet', data.scope1Fleet.toFixed(2), pct(data.scope1Fleet, data.total)],
      ['GRI 305-1', 'Scope 1 — Total direct emissions', data.scope1.toFixed(2), pct(data.scope1, data.total)],
      ['GRI 305-2', 'Scope 2 — Location-based', data.scope2Location.toFixed(2), pct(data.scope2Location, data.total)],
      ['GRI 305-2', 'Scope 2 — Market-based', data.scope2Market.toFixed(2), '—'],
      ['GRI 305-3', 'Scope 3 — Business travel & commuting', data.scope3.toFixed(2), pct(data.scope3, data.total)],
      ['GRI 305-1/2/3', 'Total GHG emissions', data.total.toFixed(2), '100%'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 8 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 30 } },
    didParseCell: (hookData) => {
      if (hookData.row.index === 2 || hookData.row.index === 6) {
        hookData.cell.styles.fontStyle = 'bold'
      }
    },
  })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 15

  // ── GRI 305-4: Emissions intensity ──
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('GRI 305-4: GHG Emissions Intensity', 14, y)
  y += 10

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value', 'Unit']],
    body: [
      ['Total GHG emissions', data.total.toFixed(2), 'tCO2e'],
      ['Emissions per employee', data.perEmployee.toFixed(2), 'tCO2e / FTE'],
      ['Grid emission factor (location)', String(data.gridLocation), 'gCO2/kWh'],
      ['Grid emission factor (market)', String(data.gridMarket), 'gCO2/kWh'],
      ['Grid country', data.gridCountry, '—'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 8 },
  })

  // ── Page 2: Monthly data & methodology ──
  doc.addPage()
  y = 20

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('GRI 305: Monthly Emissions Breakdown', 14, y)
  y += 10

  autoTable(doc, {
    startY: y,
    head: [['Month', 'Scope 1 (tCO2e)', 'Scope 2 (tCO2e)', 'Scope 3 (tCO2e)', 'Total (tCO2e)']],
    body: data.monthlyData.map(m => [
      m.month,
      m.scope1.toFixed(2),
      m.scope2.toFixed(2),
      m.scope3.toFixed(2),
      m.total.toFixed(2),
    ]),
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 8 },
    foot: [['Annual Total',
      data.monthlyData.reduce((a, m) => a + m.scope1, 0).toFixed(2),
      data.monthlyData.reduce((a, m) => a + m.scope2, 0).toFixed(2),
      data.monthlyData.reduce((a, m) => a + m.scope3, 0).toFixed(2),
      data.monthlyData.reduce((a, m) => a + m.total, 0).toFixed(2),
    ]],
    footStyles: { fillColor: [243, 244, 246], textColor: [0, 0, 0], fontStyle: 'bold' },
  })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 15

  // ── Methodology & Data Sources ──
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Methodology & Data Quality', 14, y)
  y += 8
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(80, 80, 80)

  const methodology = [
    'Reporting framework: GRI Standards 2021 (GRI 2, GRI 305)',
    'GHG accounting: GHG Protocol Corporate Accounting and Reporting Standard',
    'Consolidation approach: Operational control',
    'Gases included: CO2, CH4, N2O (CO2 equivalent using AR5 GWP values)',
    `Scope 1: DEFRA/DESNZ Conversion Factors ${data.reportingYear}`,
    'Scope 2: Dual reporting — location-based (IEA/EEA production mix) and market-based (AIB residual mix)',
    `Grid factors: ${data.gridCountry} — ${data.gridLocation} gCO2/kWh (location) / ${data.gridMarket} gCO2/kWh (market)`,
    `Scope 3: DEFRA factors — Category 6 (business travel), Category 7 (employee commuting)`,
    'Base year: Not established (first reporting period)',
    'All emission factors stored in auditable PostgreSQL database with full source traceability',
  ]

  methodology.forEach(line => {
    doc.text('  •  ' + line, 14, y)
    y += 5
  })

  y += 5
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text('GRI Content Index', 14, y)
  y += 10

  autoTable(doc, {
    startY: y,
    head: [['GRI Standard', 'Disclosure', 'Location']],
    body: [
      ['GRI 2: General Disclosures 2021', '2-1 Organization details', 'Page 1'],
      ['GRI 2: General Disclosures 2021', '2-3 Reporting period', 'Page 1'],
      ['GRI 2: General Disclosures 2021', '2-5 External assurance', 'Page 1'],
      ['GRI 2: General Disclosures 2021', '2-6 Activities, value chain', 'Page 1'],
      ['GRI 2: General Disclosures 2021', '2-7 Employees', 'Page 1'],
      ['GRI 305: Emissions 2016', '305-1 Direct (Scope 1) GHG', 'Page 1'],
      ['GRI 305: Emissions 2016', '305-2 Indirect (Scope 2) GHG', 'Page 1'],
      ['GRI 305: Emissions 2016', '305-3 Other indirect (Scope 3) GHG', 'Page 1'],
      ['GRI 305: Emissions 2016', '305-4 GHG emissions intensity', 'Page 1'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 7 },
    columnStyles: { 0: { cellWidth: 55 } },
  })

  addFooters(doc, 'GRI Standards 2021')
  return doc
}

// ════════════════════════════════════════════════════════════════════════════
//  ESRS E1 Climate Change Report (CSRD)
// ════════════════════════════════════════════════════════════════════════════

export function generateESRSReport(data: ReportData): jsPDF {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  // ── Header — green accent for ESRS ──
  doc.setFillColor(5, 150, 105) // emerald-600
  doc.rect(0, 0, pageWidth, 44, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('ESRS E1 — Climate Change', 14, 18)
  doc.setFontSize(11)
  doc.text('European Sustainability Reporting Standards (CSRD)', 14, 28)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`${data.companyName} · Reporting Year ${data.reportingYear}`, 14, 38)

  y = 58
  doc.setTextColor(0, 0, 0)

  // ── E1-1: Transition plan for climate change mitigation ──
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text('E1-1  Transition Plan for Climate Change Mitigation', 14, y)
  y += 8
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(80, 80, 80)

  const transitionItems = [
    `${data.companyName} operates in the ${data.industry} sector (NACE: ${data.naceCode}) in ${data.country}.`,
    `Total GHG footprint for ${data.reportingYear}: ${data.total.toFixed(2)} tCO2e across Scope 1, 2, and 3.`,
    'The undertaking is assessing pathways to reduce emissions in line with the Paris Agreement targets.',
    'Key levers identified: energy efficiency, renewable energy procurement, fleet electrification.',
    'A detailed transition plan with milestones is under development.',
  ]

  transitionItems.forEach(line => {
    const lines = doc.splitTextToSize(line, pageWidth - 32)
    doc.text(lines, 18, y)
    y += lines.length * 4.5
  })

  y += 6
  doc.setTextColor(0, 0, 0)

  // ── E1-4: Targets related to climate change mitigation ──
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text('E1-4  Targets Related to Climate Change', 14, y)
  y += 10

  autoTable(doc, {
    startY: y,
    head: [['Target', 'Baseline', 'Target Year', 'Reduction', 'Status']],
    body: [
      ['Scope 1+2 reduction', `${(data.scope1 + data.scope2Location).toFixed(1)} tCO2e (${data.reportingYear})`, '2030', '-42%', 'In progress'],
      ['Renewable electricity', '0% (assumed)', '2028', '100%', 'Planned'],
      ['Fleet electrification', `${data.scope1Fleet.toFixed(1)} tCO2e fleet`, '2030', '-50%', 'Planned'],
      ['Supply chain engagement', `${data.scope3.toFixed(1)} tCO2e Scope 3`, '2030', '-25%', 'Assessment'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [5, 150, 105] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 8 },
  })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 15

  // ── E1-6: Gross Scopes 1, 2, 3 and Total GHG emissions ──
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text('E1-6  Gross GHG Emissions', 14, y)
  y += 10

  const totalMarket = data.scope1 + data.scope2Market + data.scope3

  autoTable(doc, {
    startY: y,
    head: [['ESRS Datapoint', 'Category', 'tCO2e', '% of Total']],
    body: [
      ['E1-6 §44(a)', 'Scope 1 — Stationary combustion', data.scope1Stationary.toFixed(2), pct(data.scope1Stationary, data.total)],
      ['E1-6 §44(a)', 'Scope 1 — Mobile combustion (fleet)', data.scope1Fleet.toFixed(2), pct(data.scope1Fleet, data.total)],
      ['', 'Scope 1 — Total gross direct', data.scope1.toFixed(2), pct(data.scope1, data.total)],
      ['E1-6 §44(b)', 'Scope 2 — Location-based', data.scope2Location.toFixed(2), pct(data.scope2Location, data.total)],
      ['E1-6 §44(b)', 'Scope 2 — Market-based', data.scope2Market.toFixed(2), pct(data.scope2Market, totalMarket)],
      ['E1-6 §44(c)', 'Scope 3 — Cat. 6 Business travel', (data.scope3 * 0.6).toFixed(2), '—'],
      ['E1-6 §44(c)', 'Scope 3 — Cat. 7 Employee commuting', (data.scope3 * 0.4).toFixed(2), '—'],
      ['', 'Scope 3 — Total', data.scope3.toFixed(2), pct(data.scope3, data.total)],
      ['E1-6 §50', 'Total GHG (location-based)', data.total.toFixed(2), '100%'],
      ['E1-6 §50', 'Total GHG (market-based)', totalMarket.toFixed(2), '—'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [5, 150, 105] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 8 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 28 } },
    didParseCell: (hookData) => {
      if (hookData.row.index === 2 || hookData.row.index === 7 || hookData.row.index === 8 || hookData.row.index === 9) {
        hookData.cell.styles.fontStyle = 'bold'
      }
    },
  })

  // ── Page 2: Intensity, monthly, methodology ──
  doc.addPage()
  y = 20

  // ── E1-6: GHG intensity per net revenue ──
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text('E1-6  GHG Intensity Metrics', 14, y)
  y += 10

  autoTable(doc, {
    startY: y,
    head: [['ESRS Datapoint', 'Metric', 'Value', 'Unit']],
    body: [
      ['E1-6 §53', 'GHG intensity per employee (Scope 1+2)', ((data.scope1 + data.scope2Location) / (data.headcount || 1)).toFixed(3), 'tCO2e / FTE'],
      ['E1-6 §53', 'GHG intensity per employee (total)', data.perEmployee.toFixed(3), 'tCO2e / FTE'],
      ['E1-6 §44(b)', 'Grid emission factor — location', String(data.gridLocation), 'gCO2/kWh'],
      ['E1-6 §44(b)', 'Grid emission factor — market (residual)', String(data.gridMarket), 'gCO2/kWh'],
      ['', 'Grid country', data.gridCountry, '—'],
      ['', 'Total FTE headcount', String(data.headcount), 'employees'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [5, 150, 105] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 8 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 28 } },
  })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 15

  // ── Monthly breakdown ──
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text('Monthly GHG Emissions Trend', 14, y)
  y += 10

  autoTable(doc, {
    startY: y,
    head: [['Month', 'Scope 1', 'Scope 2', 'Scope 3', 'Total (tCO2e)']],
    body: data.monthlyData.map(m => [
      m.month,
      m.scope1.toFixed(2),
      m.scope2.toFixed(2),
      m.scope3.toFixed(2),
      m.total.toFixed(2),
    ]),
    theme: 'striped',
    headStyles: { fillColor: [5, 150, 105] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 8 },
    foot: [['Annual Total',
      data.monthlyData.reduce((a, m) => a + m.scope1, 0).toFixed(2),
      data.monthlyData.reduce((a, m) => a + m.scope2, 0).toFixed(2),
      data.monthlyData.reduce((a, m) => a + m.scope3, 0).toFixed(2),
      data.monthlyData.reduce((a, m) => a + m.total, 0).toFixed(2),
    ]],
    footStyles: { fillColor: [236, 253, 245], textColor: [0, 0, 0], fontStyle: 'bold' },
  })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 15

  // ── E1-1 / E1-9: Methodology & policies ──
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text('Methodology, Policies & Data Quality (E1-1, E1-9)', 14, y)
  y += 8
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(80, 80, 80)

  const esrsMethodology = [
    'Reporting standard: ESRS E1 Climate Change (Delegated Regulation (EU) 2023/2772)',
    'GHG accounting: GHG Protocol Corporate Standard — operational control approach',
    'Gases reported: CO2, CH4, N2O expressed as CO2-equivalents (IPCC AR5 GWP)',
    `Scope 1: DEFRA/DESNZ ${data.reportingYear} emission factors for stationary combustion and company vehicles`,
    'Scope 2: Dual reporting — location-based (IEA/EEA production mix) and market-based (AIB residual mix)',
    `Grid factors: ${data.gridCountry} — ${data.gridLocation} gCO2/kWh (location) / ${data.gridMarket} gCO2/kWh (market)`,
    'Scope 3: Categories 6 (business travel) and 7 (employee commuting) per GHG Protocol Scope 3 Standard',
    'Significant Scope 3 categories (1, 2, 3, 11) not yet quantified — to be included in future reporting',
    'No use of carbon credits or offsets in reported figures',
    'Emission factors sourced from auditable database with full provenance tracking',
    'Financial materiality assessment: Climate risks identified as material per double materiality analysis',
  ]

  esrsMethodology.forEach(line => {
    const lines = doc.splitTextToSize('  •  ' + line, pageWidth - 28)
    doc.text(lines, 14, y)
    y += lines.length * 4.5
  })

  // ── Page 3: ESRS E1 Disclosure Index ──
  doc.addPage()
  y = 20

  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text('ESRS E1 Disclosure Requirement Index', 14, y)
  y += 10

  autoTable(doc, {
    startY: y,
    head: [['Disclosure', 'Title', 'Status', 'Location']],
    body: [
      ['E1-1', 'Transition plan for climate change mitigation', 'Partial', 'Page 1'],
      ['E1-2', 'Policies related to climate change mitigation and adaptation', 'Planned', '—'],
      ['E1-3', 'Actions and resources related to climate change policies', 'Planned', '—'],
      ['E1-4', 'Targets related to climate change mitigation and adaptation', 'Partial', 'Page 1'],
      ['E1-5', 'Energy consumption and mix', 'Planned', '—'],
      ['E1-6', 'Gross Scopes 1, 2, 3 and total GHG emissions', 'Reported', 'Pages 1-2'],
      ['E1-7', 'GHG removals and storage', 'Not applicable', '—'],
      ['E1-8', 'Internal carbon pricing', 'Not applicable', '—'],
      ['E1-9', 'Anticipated financial effects from climate change', 'Planned', '—'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [5, 150, 105] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 8 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 18 }, 2: { cellWidth: 28 } },
    didParseCell: (hookData) => {
      if (hookData.section === 'body' && hookData.column.index === 2) {
        const val = hookData.cell.raw as string
        if (val === 'Reported') hookData.cell.styles.textColor = [5, 150, 105]
        else if (val === 'Partial') hookData.cell.styles.textColor = [217, 119, 6]
        else if (val === 'Planned') hookData.cell.styles.textColor = [107, 114, 128]
        else hookData.cell.styles.textColor = [156, 163, 175]
      }
    },
  })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 15

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(80, 80, 80)
  doc.text('Disclaimer', 14, y)
  y += 6
  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  const disclaimer = doc.splitTextToSize(
    'This report is prepared in accordance with ESRS E1 Climate Change as part of the Corporate Sustainability Reporting Directive (CSRD). ' +
    'Data has been collected using the Hosmos platform. Where actual data was unavailable, estimates based on recognized emission factors have been used. ' +
    'This report has not been externally assured. The undertaking intends to expand reporting scope and obtain limited assurance in subsequent reporting periods.',
    pageWidth - 28
  )
  doc.text(disclaimer, 14, y)

  addFooters(doc, 'ESRS E1 Climate Change (CSRD)')
  return doc
}
